const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const app=fs.readFileSync('app/src/main/assets/app.js','utf8');
const take=(a,b)=>{const start=app.indexOf(a),end=app.indexOf(b,start);assert(start>=0&&end>start);return app.slice(start,end);};
const plain=x=>JSON.parse(JSON.stringify(x));
const norm=x=>String(x||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const cup={date:'2099-10-10',competition:'U9 Selkent Cup Two - Round 1',opponent:'Opponent One',venue:'A'};
const second={...cup,opponent:'Opponent Two',venue:'H'};
function context(fixtures=[cup,second],grounds=[]){
 const nodes=new Map();
 for(const id of ['next-match-confirmation-editor','fixture-confirm-details','next-match-share','next-match-confirm-time-label','next-match-ground-select','next-match-confirm-time','next-match-kit-choice','next-match-manual-ground','next-match-manual-address','next-match-manual-ground-fields'])nodes.set(id,{value:'',innerHTML:'',classList:{toggle(){} }});
 const c={CLOUD_MODE:true,state:{selkent:{fixtures,fixtureOverrides:{},directoryDetails:{[norm('Opponent One')]:{groundOptions:grounds}}}},document:{getElementById:id=>nodes.get(id)||null},window:{ClubHubCloud:{canEdit:()=>true}},isCoach:()=>true,ageGroupNumber:()=>9,selkentNorm:norm,matchTeamLabel:x=>x,ownTeamDisplayName:()=> 'Our Team',fixtureKitSelectionKey:f=>f.opponent,fixtureKitChoice:()=> 'home',esc:x=>String(x),nextPublishedFixture:()=>fixtures[0],fixtureOverviewContext:()=>({ownProfile:{home:'Green'}}),knownKit:()=>true,matchdayArrivalTime:t=>/^\d\d:\d\d$/.test(t),saveState:()=>c.saved=true,auditEvent:()=>{},fixtureFingerprint:()=> 'fingerprint',fixtureStableKey:()=> 'key',renderNextMatch:()=>{},renderMatchPageNextFixture:()=>{},renderSelkentFixtures:()=>{},renderMatchdayDashboard:()=>{},toast:x=>c.message=x,nodes};
 vm.createContext(c);
 vm.runInContext(take('function miniCupGroup(', 'function fixtureCompetitionLabel(')+take('function fixtureOverride(', 'function pilotKitDefaults(')+take('function homeFixtureTeamNames(', 'async function openNextFixtureDetails(')+take('function saveFixtureConfirmation(){','function shareCardWrap('),c);
 return c;
}
const options=[{name:'Opponent Ground A',address:'Road A'},{name:'Opponent Ground B',address:'Road B'}],before=plain(options);
const c=context(undefined,options);
c.renderFixtureConfirmationEditor(cup);
assert.equal(c.nodes.get('next-match-ground-select').value,'0');
assert.deepEqual(plain(c.groundOptionsForFixture(cup)[0]),{name:'Marathon Sports Ground',address:'Shooters Hill'});
assert.equal(c.nodes.get('next-match-confirm-time').value,'','no group time is invented');
c.nodes.get('next-match-confirm-time').value='14:00';
c.saveFixtureConfirmation();
assert(c.saved);assert.equal(c.state.selkent.fixtureOverrides[cup.opponent].groundName,'Marathon Sports Ground');assert.equal(c.state.selkent.fixtureOverrides[cup.opponent].address,'Shooters Hill');
assert.deepEqual(plain(options),before,'directory grounds are not mutated');
const changed=context(undefined,options);
changed.state.selkent.fixtureOverrides[second.opponent]={groundName:'Confirmed Alternate Ground',address:'Alternate Road',time:'13:00',confirmedAt:'2099-10-01'};
changed.renderFixtureConfirmationEditor(cup);
assert.deepEqual(plain(changed.groundOptionsForFixture(cup)[0]),{name:'Confirmed Alternate Ground',address:'Alternate Road'});
assert.equal(changed.nodes.get('next-match-ground-select').value,'0');
const editing=context(undefined,options);
editing.state.selkent.fixtureOverrides[cup.opponent]={groundName:'Manual Ground',address:'Manual Address',time:'15:00'};
editing.renderFixtureConfirmationEditor(cup);
assert.equal(editing.nodes.get('next-match-ground-select').value,'__other__');assert.equal(editing.nodes.get('next-match-manual-ground').value,'Manual Ground');
const duplicate=context(undefined,[{name:'Marathon Sports Ground',address:'Shooters Hill'},...options]);
assert.equal(duplicate.groundOptionsForFixture(cup).length,3,'default ground is not duplicated');
const ordinary={...cup,competition:'League'};
const league=context([ordinary],options);league.renderFixtureConfirmationEditor(ordinary);
assert.deepEqual(plain(league.groundOptionsForFixture(ordinary)),options);assert.equal(league.nodes.get('next-match-ground-select').value,'','ordinary multi-ground choice stays explicit');
const single=context([ordinary],[options[0]]);single.renderFixtureConfirmationEditor(ordinary);assert.equal(single.nodes.get('next-match-ground-select').value,'0');
const locked=context();locked.window.ClubHubCloud.canEdit=()=>false;locked.renderFixtureConfirmationEditor(cup);locked.nodes.get('next-match-confirm-time').value='14:00';locked.saveFixtureConfirmation();assert.equal(locked.saved,undefined,'cloud save permission remains mandatory');
console.log('PASS Cup confirmation uses the displayed default or confirmed venue, preserves manual and ordinary choices, and retains save permissions');
