const assert=require('node:assert/strict');
const fs=require('node:fs');
const app=fs.readFileSync('app/src/main/assets/app.js','utf8');
const css=fs.readFileSync('app/src/main/assets/app-design-system.css','utf8');
assert.match(app,/function cupPairCardHtml\(f\)/);
assert.match(app,/function groupedUpcomingFixtures\(fixtures=upcomingFixtures\(\)\)/);
assert.match(app,/function groupFixtureCardHtmlV15\(f,index,parent=false\)/);
assert.doesNotMatch(app,/_cupPair/);
assert.match(app,/function canonicalMatchRowsHtml\(f=\{\}\)/);
assert.doesNotMatch(app,/Three games run back to back\. The running order/);
assert.match(css,/\.cup-pair-fixture-card/);
console.log('PASS Cup group is one event with canonical home-first game rows');
