const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/app.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/index.html'),'utf8');
const start=source.indexOf('let __tacticsSelected=null;');
const end=source.indexOf('function renderMatchdaySquadPicker(){',start);
const reset=source.slice(source.indexOf('function resetTactics(){'),source.indexOf('\nfunction renderSquad(){'));
assert.ok(start>0&&end>start&&reset.startsWith('function resetTactics(){'));
const players=Array.from({length:8},(_,i)=>({number:i+1,name:`Player ${i+1}`}));
let fixture={id:'first'};
let limited=true;
const state={selkent:{},tactics:{lineup:[],positions:{},formationByFixture:{},matchdaySelections:{},matchdayAutoPrepared:{}}};
const context={state,fixture,footballFormat:()=>({onPitch:5,matchday:7}),activePlayers:()=>players,
  requiresMatchdaySelection:()=>limited,
  nextPublishedFixture:()=>fixture,fixtureStableKey:f=>f.id,requireCoach:()=>true,isCoach:()=>true,
  featureEnabled:()=>true,document:{querySelectorAll:()=>[]},auditEvent:()=>{},toast:()=>{},saveState:()=>{context.rememberTacticsPlan();}};
vm.createContext(context);vm.runInContext(source.slice(start,end)+reset,context);
const ids=()=>Array.from(context.currentMatchdaySelection());
assert.deepEqual(ids(),[],'a new fixture starts with no players chosen');
state.tactics.matchdaySelections.first=['p2','p1','p3'];
state.tactics.matchdayAutoPrepared.first=true;
context.ensureTacticsState();
state.tactics.lineup=['p3','p2','p1'];
state.tactics.positions.p3={x:31,y:41};context.rememberTacticsPlan();
fixture={id:'second'};context.ensureTacticsState();
assert.deepEqual(ids(),[],'the next fixture does not copy another fixture’s squad');
state.tactics.matchdaySelections.second=['p4'];state.tactics.matchdayAutoPrepared.second=true;context.ensureTacticsState();
state.tactics.positions.p4={x:65,y:30};context.rememberTacticsPlan();
fixture={id:'first'};context.ensureTacticsState();
assert.deepEqual(ids(),['p2','p1','p3']);
assert.deepEqual(Array.from(state.tactics.lineup),['p3','p2','p1'],'lineup order survives fixture switch');
assert.equal(state.tactics.positions.p3.x,31,'pitch position survives fixture switch');
context.resetTactics();
assert.deepEqual(ids(),['p2','p1','p3'],'reset positions preserves the matchday squad');
state.tactics.matchdaySelections.first=[];context.ensureTacticsState();
assert.deepEqual(ids(),[],'an intentionally empty selection stays empty');
fixture={id:'legacy'};state.tactics.matchdaySelections.legacy=players.slice(0,7).map(p=>`p${p.number}`);context.ensureTacticsState();
assert.deepEqual(ids(),[],'old automatic roster order is not presented as a coach selection');
limited=false;fixture={id:'first'};context.ensureTacticsState();
assert.deepEqual(ids(),players.map(p=>`p${p.number}`),'rolling substitutions use the full active roster');
assert.equal(state.tactics.matchdaySelections.first,undefined,'old fixture selection no longer limits a rolling squad');
assert.equal(state.tactics.lineup.length,players.length,'bench includes all players beyond the on-pitch format');
context.resetTactics();
assert.equal(state.tactics.lineup.length,players.length,'reset positions preserves the rolling squad');
assert.ok(html.indexOf('id="matchday-squad-picker"')<html.indexOf('id="tactics-pitch"'),'squad picker appears before pitch');
assert.match(html,/id="reset-tactics"[^>]*>Reset positions/);
console.log('Tactics fixture plan checks passed');
