const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('app/src/main/assets/app.js','utf8');
const away={date:'2099-10-04',opponent:'Example Opponent',venue:'A',competition:'Division',time:''};
const home={...away,venue:'H'};
const later={...home,date:'2099-10-05',opponent:'Later Opponent',time:'08:00'};
const earlier={...home,date:'2099-10-03',opponent:'Earlier Opponent',time:''};
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const key=f=>`${f.date}|${norm(f.opponent)}|${f.venue}|${norm(f.competition)}`;
const context={state:{selkent:{fixtures:[away,home,later],fixtureOverrides:{[key(home)]:{time:'14:00',groundName:'Example Field',address:'Example Road',confirmedAt:'2099-10-01T09:00:00Z'}}}},fixtureKitSelectionKey:key,fixtureIsReported:()=>false};
vm.runInNewContext(source.slice(source.indexOf('function fixtureOverride(f={}){'),source.indexOf('function pilotKitDefaults(')),context);
vm.runInNewContext(source.slice(source.indexOf('function upcomingFixtures(){'),source.indexOf('function fixtureCompetitionLabel(')),context);
assert.equal(context.nextPublishedFixture().venue,'H','the confirmed time selects the correct same-day fixture');
assert.equal(context.resolvedFixture(context.nextPublishedFixture()).time,'14:00');
context.state.selkent.fixtures.push(earlier);
assert.equal(context.nextPublishedFixture().date,earlier.date,'a confirmation never skips a fixture on an earlier date');
assert.equal(away.time,'','ordering preserves the public fixture records');
console.log('PASS confirmed fixture times control same-day order while preserving date order');
