const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const app=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/app.js'),'utf8');
const start=app.indexOf('function requiresMatchdaySelection(){');
const end=app.indexOf('\nfunction selkentMinimumPlayers(',start);
assert.ok(start>0&&end>start);
let rule=null;
const context={competitionRuleForAge:()=>rule,ageGroupNumber:()=>9};
vm.createContext(context);vm.runInContext(app.slice(start,end),context);
assert.equal(context.requiresMatchdaySelection(),false,'unknown competition rule does not force selection');
rule={rolling_substitutions:true,max_registered:16,matchday_max:14};
assert.equal(context.requiresMatchdaySelection(),true,'a smaller matchday cap still requires selection with rolling substitutions');
rule={rolling_substitutions:true,max_registered:14,matchday_max:14};
assert.equal(context.requiresMatchdaySelection(),false,'rolling substitutions do not require selection when the full roster fits the matchday cap');
rule={rolling_substitutions:false,max_registered:18,matchday_max:16};
assert.equal(context.requiresMatchdaySelection(),true,'standard substitutions with a real matchday cap require selection');
rule={rolling_substitutions:false,max_registered:10,matchday_max:10};
assert.equal(context.requiresMatchdaySelection(),false,'equal roster and matchday limits do not require selection');
assert.match(app,/picker=document\.getElementById\('matchday-squad-picker'\),limited=requiresMatchdaySelection\(\);picker\?\.classList\.toggle\('hidden',!limited\);if\(!limited\)return/);
assert.match(app,/notifyBtn\.classList\.toggle\('hidden',!isCoach\(\)\|\|!requiresMatchdaySelection\(\)\)/);
console.log('Matchday selection rules checks passed');
