-- DRAFT. NOT APPLIED. Needs Mike's approval and a Supabase branch test first.
-- Problem: claim_invite maps every unrecognised invite role (including 'player') to an
-- approved 'coach'. No player invites exist today (10 coach, 4 parent, 1 club_admin).
-- Fix outline (apply inside claim_invite's v_role CASE and approval logic):
--   when inv.role='player' then 'player'
-- and keep approved_at/approved_by NULL for players until a coach approves.
-- Also: reject unknown roles instead of defaulting to coach:
--   else raise exception 'Unsupported invite role';
-- Also add: ALTER TABLE profiles ADD CONSTRAINT profiles_role_check
--   CHECK (role in ('club_admin','coach','assistant_coach','parent','player','pending','pending_parent','revoked'));
-- Also fix parent_player_links_insert: replace "p.club_id = p.club_id" with
--   "p.club_id = parent_player_links.club_id".
